fix: delete conversation
henefisa/xfs-chat-app-backend pull request #165
Opened 2023-01-01 09:22 UTC by luantrum27

2023-01-02 02:57 UTC, henefisa requested changes

2023-01-02 02:57 UTC, henefisa commented on src/entities/conversation-archived.entity.ts
> +  deleteAt: string;
deletedAt

2023-01-02 02:57 UTC, henefisa commented on src/services/conversation.service.ts
> +  conversationArchived.deleteAt = moment().toISOString();
why?

2023-01-02 03:20 UTC, luantrum27 commented on src/services/conversation.service.ts
> +  conversationArchived.deleteAt = moment().toISOString();
vì deleteAt em để string á nên phải ép kiểu á

2023-01-03 04:42 UTC, henefisa commented on src/entities/conversation-archived.entity.ts
> -    },
sao xóa cái này vậy

2023-01-03 13:27 UTC, henefisa commented on src/entities/conversation-archived.entity.ts
> +  deletedAt: string;
string -> Moment

2023-01-03 13:27 UTC, henefisa approved these changes

2023-01-03 16:24 UTC, merged