feat(server): setup peer server
henefisa/xfs-chat-app-backend pull request #193
Opened 2023-02-05 11:56 UTC by pinkhuy1004

2023-02-05 12:10 UTC, henefisa requested changes

2023-02-05 12:10 UTC, henefisa commented on src/configs/Peer.ts
> +    readonly cleanup_out_msgs?: number;
camelCase

2023-02-05 12:12 UTC, pinkhuy1004 commented on src/configs/Peer.ts
> +    readonly cleanup_out_msgs?: number;
type was get from library, just copy it

2023-02-05 12:14 UTC, pinkhuy1004 commented on src/configs/Peer.ts
> +    readonly cleanup_out_msgs?: number;
![image](https://user-images.githubusercontent.com/58259694/216818085-1b420800-2ee9-4801-ab94-f563bd39ee34.png)

2023-02-06 02:51 UTC, henefisa approved these changes

2023-02-06 02:51 UTC, merged