Feature/send message
henefisa/xfs-chat-app-backend pull request #49
Opened 2022-11-09 16:02 UTC by luantrum27

2022-11-10 04:22 UTC, henefisa requested changes

2022-11-10 04:22 UTC, henefisa commented on src/routes/index.ts
> +router.use('/conversation', ConversationRoutes);
conversations

2022-11-10 05:40 UTC, luantrum27 commented on src/routes/index.ts
> +router.use('/conversation', ConversationRoutes);
Oke anh

2022-11-11 04:29 UTC, henefisa approved these changes

2022-11-11 04:29 UTC, merged