Refactor/hide delete message
henefisa/xfs-chat-app-backend pull request #58
Opened 2022-11-12 12:07 UTC by luantrum27

2022-11-13 10:00 UTC, henefisa requested changes

2022-11-13 10:00 UTC, henefisa commented on src/entities/hide-message.entity.ts
> +}
chưa hiểu nó có tác dụng gì

2022-11-13 10:00 UTC, henefisa commented on src/entities/message.entity.ts
> +  hideMessage: HideMessage[];
user có cần lấy hide message đâu, mà lại cần relation

2022-11-13 10:00 UTC, henefisa commented on src/exceptions/invalid.exception.ts
> +export class InValidException extends HttpException {
InValidException  -> InvalidException

2022-11-14 15:58 UTC, theluanhoang commented on src/entities/hide-message.entity.ts
> +}
cái này xóa tin nhắn 1 phía á anh

2022-11-14 16:00 UTC, luantrum27 commented on src/entities/message.entity.ts
> +  hideMessage: HideMessage[];
Em nối với message để khi lấy tin nhắn của cuộc hội thoại, em sẽ lấy những tin nhắn khong nằm trong hideMessage á anh

2022-11-15 04:06 UTC, closed without merging